package store

import (
	"database/sql"
	"errors"
	"regexp"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5/pgconn"
)

// dbx wraps the database so every query is written once, SQLite style
// (? placeholders, INTEGER / REAL columns), and rewritten for PostgreSQL.
type dbx struct {
	*sql.DB
	pg bool
}

func (d *dbx) Exec(query string, args ...any) (sql.Result, error) {
	return d.DB.Exec(rebind(d.pg, query), args...)
}

func (d *dbx) Query(query string, args ...any) (*sql.Rows, error) {
	return d.DB.Query(rebind(d.pg, query), args...)
}

func (d *dbx) QueryRow(query string, args ...any) *sql.Row {
	return d.DB.QueryRow(rebind(d.pg, query), args...)
}

func (d *dbx) Begin() (*txx, error) {
	tx, err := d.DB.Begin()
	if err != nil {
		return nil, err
	}
	return &txx{tx, d.pg}, nil
}

type txx struct {
	*sql.Tx
	pg bool
}

func (t *txx) Exec(query string, args ...any) (sql.Result, error) {
	return t.Tx.Exec(rebind(t.pg, query), args...)
}

func (t *txx) Query(query string, args ...any) (*sql.Rows, error) {
	return t.Tx.Query(rebind(t.pg, query), args...)
}

func (t *txx) QueryRow(query string, args ...any) *sql.Row {
	return t.Tx.QueryRow(rebind(t.pg, query), args...)
}

func (t *txx) Prepare(query string) (*sql.Stmt, error) {
	return t.Tx.Prepare(rebind(t.pg, query))
}

// rebind turns ? placeholders into PostgreSQL's $1, $2, ... (quoted text is
// left alone).
func rebind(pg bool, query string) string {
	if !pg || !strings.Contains(query, "?") {
		return query
	}
	var sb strings.Builder
	sb.Grow(len(query) + 16)
	n, quoted := 0, false
	for i := 0; i < len(query); i++ {
		c := query[i]
		switch {
		case c == '\'':
			quoted = !quoted
		case c == '?' && !quoted:
			n++
			sb.WriteByte('$')
			sb.WriteString(strconv.Itoa(n))
			continue
		}
		sb.WriteByte(c)
	}
	return sb.String()
}

var (
	reAutoID  = regexp.MustCompile(`\bINTEGER PRIMARY KEY AUTOINCREMENT\b`)
	reInteger = regexp.MustCompile(`\bINTEGER\b`)
	reReal    = regexp.MustCompile(`\bREAL\b`)
)

// ddl adapts SQLite column types for PostgreSQL: 64-bit integers (unix ms
// timestamps do not fit in PostgreSQL's 32-bit INTEGER), double precision
// floats and identity ids.
func (d *dbx) ddl(s string) string {
	if !d.pg {
		return s
	}
	s = reAutoID.ReplaceAllString(s, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	s = reInteger.ReplaceAllString(s, "BIGINT")
	return reReal.ReplaceAllString(s, "DOUBLE PRECISION")
}

// resetID moves a table's id sequence past rows inserted with explicit ids
// (PostgreSQL only; SQLite tracks this by itself).
func (t *txx) resetID(table string) error {
	if !t.pg {
		return nil
	}
	_, err := t.Tx.Exec(`SELECT setval(pg_get_serial_sequence('` + table + `', 'id'), COALESCE((SELECT MAX(id) FROM ` + table + `), 0) + 1, false)`)
	return err
}

// uniqueField names the column behind a unique constraint violation, or ""
// for other errors.
func uniqueField(err error) string {
	if err == nil {
		return ""
	}
	var pe *pgconn.PgError
	if errors.As(err, &pe) {
		// Detail: Key (prefix)=(oa) already exists.
		if pe.Code == "23505" {
			if i, j := strings.Index(pe.Detail, "("), strings.Index(pe.Detail, ")"); i >= 0 && j > i {
				return pe.Detail[i+1 : j]
			}
			return "value"
		}
		return ""
	}
	// SQLite: constraint failed: UNIQUE constraint failed: providers.prefix (2067)
	const marker = "UNIQUE constraint failed: "
	msg := err.Error()
	i := strings.Index(msg, marker)
	if i < 0 {
		return ""
	}
	col, _, _ := strings.Cut(msg[i+len(marker):], " ")
	col, _, _ = strings.Cut(col, ",") // composite keys: name the first column
	if j := strings.LastIndex(col, "."); j >= 0 {
		col = col[j+1:]
	}
	return col
}
