package store

import (
	"os"
	"strings"
	"testing"
)

func TestRebind(t *testing.T) {
	cases := map[string]string{
		`SELECT 1`:                        `SELECT 1`,
		`a=? AND b=?`:                     `a=$1 AND b=$2`,
		`k='what?' AND v=?`:               `k='what?' AND v=$1`,
		`v='it''s?' OR w=? OR x IN (?,?)`: `v='it''s?' OR w=$1 OR x IN ($2,$3)`,
		"INSERT INTO t (a, b) VALUES (?,?) RETURNING id": "INSERT INTO t (a, b) VALUES ($1,$2) RETURNING id",
	}
	for in, want := range cases {
		if got := rebind(true, in); got != want {
			t.Errorf("rebind(%q) = %q, want %q", in, got, want)
		}
		if got := rebind(false, in); got != in {
			t.Errorf("SQLite query changed: %q", got)
		}
	}
	d := &dbx{pg: true}
	if got := d.ddl("id INTEGER PRIMARY KEY AUTOINCREMENT, n INTEGER NOT NULL, c REAL, s TEXT"); got !=
		"id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, n BIGINT NOT NULL, c DOUBLE PRECISION, s TEXT" {
		t.Errorf("ddl: %s", got)
	}
}

// Behaviour that differs between the two databases; runs on PostgreSQL when
// AI_ROUTE_TEST_DATABASE_URL is set.
func TestBackendSpecifics(t *testing.T) {
	st, err := openTest(t)
	if err != nil {
		t.Fatal(err)
	}
	defer st.Close()
	want := "sqlite"
	if os.Getenv("AI_ROUTE_TEST_DATABASE_URL") != "" {
		want = "postgres"
	}
	if st.Backend() != want {
		t.Fatalf("backend %s, want %s", st.Backend(), want)
	}

	// unique violations read the same on both
	a, b := &Provider{Prefix: "a", OpenAIBaseURL: "http://a/v1"}, &Provider{Prefix: "b", OpenAIBaseURL: "http://b/v1"}
	mustNil(t, st.CreateProvider(a))
	mustNil(t, st.CreateProvider(b))
	b.Prefix = "a"
	if err := st.UpdateProvider(b); err == nil || err.Error() != "prefix already exists" {
		t.Fatalf("duplicate prefix: %v", err)
	}
	mustNil(t, st.CreateModel(&Model{Name: "m", Targets: []string{"a/x"}}))
	if err := st.CreateModel(&Model{Name: "m", Targets: []string{"a/x"}}); err == nil || err.Error() != "name already exists" {
		t.Fatalf("duplicate model: %v", err)
	}

	// keys imported with explicit ids must not collide with keys created later
	e, _ := st.Export()
	e.Keys = []*APIKey{{ID: 7, Name: "imported", Key: "sk-route-imported-0000000000", Enabled: true}}
	mustNil(t, st.Import(e))
	k := &APIKey{Name: "new", Enabled: true}
	mustNil(t, st.CreateKey(k))
	if k.ID <= 7 {
		t.Fatalf("new key id %d collides with imported ids", k.ID)
	}

	// large values survive: unix ms timestamps and fractional costs
	st.insertLogs([]*RequestLog{{CreatedAt: 1 << 42, KeyID: k.ID, Cost: 0.000123, Currency: "USD", Error: strings.Repeat("x", 10)}})
	logs, _, err := st.QueryLogs(LogQuery{KeyID: k.ID})
	if err != nil || len(logs) != 1 || logs[0].CreatedAt != 1<<42 || logs[0].Cost != 0.000123 {
		t.Fatalf("logs: %v %+v", err, logs)
	}
}
